### ISSUE TITLE
Overridden functions with different arguments

### ISSUE THREAD

**Issue by deech** [wavewave/fficxx#12]
Hi,
I'm really excited to see all the recent activity so I tried it out. 

I tried out `MySample` and the generator looks good but I couldn't figure out how to encode an overridden method with different arguments and return values from the parent, eg. (syntax is probably wrong):
```
class A {
   virtual void a ();
   ...
}

class B : A {
   virtual int a (int x, int y);
   ...
}
```
When I did it by just adding:
```
  , Virtual ...
```
to `MySampleGen.hs` it generated two typeclasses with the same method name and different arguments which fails to compile.

**Comment by wavewave** [comment]
C++ function overloading is handled by alias in fficxx, i.e user just gives a different name to one of the overlapped functions since Haskell does not allow that kind of overriding. As you see from this code
https://github.com/wavewave/HROOT-generate/blob/3785bf397bb7d24122ab4b6676014a576d8e72e9/lib/HROOT/Data/Hist/Class.hs#L39

the last argument is the alias. Usually it was Nothing so that generated Haskell name is the same as C++, but in this case, you should give a specific non-overlapped name.

So in your example, 
```
Virtual int_ "a" [int "x", int "y"] (Just "a_of_B")
```
will work.
