### ISSUE TITLE
release 0.6

### ISSUE THREAD

**Issue by wavewave** [wavewave/fficxx#181]
it has been too long since released last version. time for release.

**Comment by LuisChDev** [comment]
Hi, I see that you fixed the haskell-src-exts issue in the current version and it compiles, but it isn't yet on Hackage, so on nixos-20.09 it is marked as broken. I understand if you're currently busy right now, but I'd be very thankful if it became available since I'm trying to port [this library](https://github.com/google/or-tools) to Haskell.

**Comment by wavewave** [comment]
0.6 uploaded.
